#!/usr/bin/php
<?php

/* This crontab adds/remove FPM pools for php 5.6 to 8.1
   for each user who uses a fpm configuration
*/
   
require_once("/usr/share/alternc/panel/class/config_nochk.php");

// first launch sync_unix since we NEED unix user to exist!
passthru("/usr/lib/alternc/install.d/alternc-nss end");

$force = (isset($argv[1]) && $argv[1]=="force");

if (getenv("DEBUG") !== false ) $verbose = true;
else $verbose = false;

$db->query("SELECT DISTINCT m.login,m.uid,sd.type FROM sub_domaines sd, membres m WHERE m.uid=sd.compte AND sd.type IN ('php56-fpm','php70-fpm','php71-fpm','php72-fpm','php73-fpm','php74-fpm','php80-fpm','php81-fpm');");

$reload=array();
$allpools=array();
$allversions=array("5.6","7.0","7.1","7.2","7.3","7.4","8.0","8.1");

// detect installed versions
foreach($allversions as $k=>$version) {
    if (!is_dir("/etc/php/$version/fpm/pool.d")) {
        unset($allversions[$k]);
    }
}


function myecho($str) {
     global $verbose;
	 if (!$verbose) return;
	 static $first=true;
	 if ($first) {
	    echo date("Y-m-d H:i:s")." Log of php7-fpm\n";
	    $first=false;
	 }
	 echo $str."\n";
}

while ($db->next_record()) {
      $version=substr($db->f("type"),3,1).".".substr($db->f("type"),4,1);
      $user=$db->f("login");
      $allpools[$version][]=$user;
      $target = sprintf("/etc/php/%s/fpm/pool.d/%s.alternc.conf", $version, $user);
      if ($force || !is_file($target)) {
          myecho("Creating php $version fpm pool for user $user");
          $template = file_get_contents("/etc/alternc/templates/php/fpm-" . $version);
          $account_root = getuserpath($user);
          $mail_account = $user . "@" . $L_FQDN;
          $arrSearch = ["%%LOGIN%%", "%%account_root%%", "%%mail_account%%"];
          $arrReplace = [$user, $account_root, $mail_account];
          $content = str_replace($arrSearch, $arrReplace, $template);
          file_put_contents($target, $content);
          $reload[$version]=$version;
      }
}

// now delete pools we don't need anymore
foreach($allversions as $version) {
    $d=opendir("/etc/php/$version/fpm/pool.d");
    while (($c=readdir($d))!==false) {
        if (preg_match('#([^\.]*).alternc.conf$#',$c,$mat)) {
            $user=$mat[1];
            if (!in_array($user,$allpools[$version])) {
                myecho("Deleting php $version fpm pool for user $user");
                @unlink("/etc/php/".$version."/fpm/pool.d/".$user.".alternc.conf");
                $reload[$version]=$version;
            }
        }
    }
}

// now reloads php fpm versions
foreach($reload as $service) {
    exec("/etc/init.d/php".$service."-fpm reload", $output, $rc);
    if ($rc != 0) echo implode("\n", $output);
}

